### ISSUE TITLE
Keys break after resizing a floating window

### ISSUE THREAD

**Issue by ThatOneOcto** [janleigh/dotfiles#18]
## After resizing windows HJKL and a few other keys don't input
I notice that this only happens when the window is floating and not tiled if that helps

**Comment by TheRealKizu** [comment]
Seems to be working on my machine 🤔
Can you give the keys that doesn't respond after resizing the windows?

**Comment by ThatOneOcto** [comment]
HJKL and a few other keys, the way I fix it is by restarting the X server, the keys do input fine when holding mod key though

**Comment by janleigh** [comment]
Been 2 weeks now and can't seem to reproduce the issue
