### ISSUE TITLE
feat: support for higher resolutions other than 1366x768

### ISSUE THREAD

**Issue by janleigh** [janleigh/dotfiles#27]
### Discussed in https://github.com/janleigh/dotfiles/discussions/22

<div type='discussions-op-text'>

<sup>Originally posted by **janleigh** February 12, 2022</sup>
as the title says.</div>

**Comment by Deathemonic** [comment]
damn how about 4k

**Comment by janleigh** [comment]
Bump as new bar is broken on higher resolutions.
