### ISSUE TITLE
suggestion: plan to move the setup to a wiki page

### ISSUE THREAD

**Issue by Deathemonic** [janleigh/dotfiles#28]
It's just a suggestion, how about instead putting the setup at the main README how about making a wiki page so the README won't get tall plus it's more organized with a wiki

**Comment by janleigh** [comment]
> It's just a suggestion, how about instead putting the setup at the main README how about making a wiki page so the README won't get tall plus it's more organized with a wiki

How about I give you write access to the repo and you do it just like I did on [this](https://github.com/rxyhn/dotfiles) repo :shipit:

**Comment by janleigh** [comment]
I think anyone can now add a page on the wiki :thinking:

**Comment by Deathemonic** [comment]
hmm I think I can make a good wiki, Yep anyone can edit and add a wiki page

**Comment by Deathemonic** [comment]
check I just added a test page

**Comment by Deathemonic** [comment]
> > It's just a suggestion, how about instead putting the setup at the main README how about making a wiki page so the README won't get tall plus it's more organized with a wiki
> 
> How about I give you write access to the repo and you do it just like I did on [this](https://github.com/rxyhn/dotfiles) repo :shipit:

bet

**Comment by Deathemonic** [comment]
here's a demo https://github.com/janleigh/dotfiles/wiki

**Comment by janleigh** [comment]
> here's a demo [janleigh/dotfiles/wiki](https://github.com/janleigh/dotfiles/wiki)

Seems good enough :thinking:

**Comment by Deathemonic** [comment]
probably needs work like adding a help page

**Comment by janleigh** [comment]
> probably needs work like adding a help page

maybe but there's mostly no issues so /shrug

**Comment by Deathemonic** [comment]
fair enough
