### ISSUE TITLE
Keybindings ?

### ISSUE THREAD

**Issue by korrykatti** [janleigh/dotfiles#32]
Can u tell where to check for the keybindings and also when fullscreen with eww bar enabled the left side of screen doesnt record mouse input

**Comment by janleigh** [comment]
You could refer to [sxhkdrc](https://github.com/janleigh/dotfiles/blob/master/cfg/sxhkd/sxhkdrc) for the keybindings for now and what do you mean by left side of screen doesn't record mouse input?

**Comment by korrykatti** [comment]
Thanks for that and when i opened eww dashboard nothing popped up and the right side ( not the left sorry ) of the screen wasn't taking any mouse inputs i could only use that side with keyboard

**Comment by korrykatti** [comment]
Did it , its now working thank you :D
