### ISSUE TITLE
Lockscreen not working.

### ISSUE THREAD

**Issue by thine-tilde** [janleigh/dotfiles#34]
Everytime I use the shortcut mod+L  I see the lockscreen with the picture and desktop name but it gets unlocked in a second without me entering my password.

I looked in ~/.local/bin/lck and deleted the entire i3lock command and only left 'i3lock' It worked that way but the lock screen was not visible its only a grey background with i3lock

**Comment by janleigh** [comment]
Can you provide any steps to reproduce the issue? The lockscreen works perfectly fine for me.

**Comment by thine-tilde** [comment]
@janleigh  Hi, to reproduce I really just do mod+L 

I tried running this directly with sh ~/.config/eww/scripts/lockScreen and sh $HOME/.local/bin/lck
And this is what I get

No players found


output 0: size(1366, 768) pos(0, 0)
i3lock: color is invalid, it must be given in 3-byte hexadecimal format: rrggbb
output 0: size(1366, 768) pos(0, 0)

No players found

**Comment by thine-tilde** [comment]
@janleigh Nevermind, it works now. Turns out yay didnt install i3lock-color because i already had i3-lock installed. I had to remove i3-lock and install i3lock-color . It works fine now.
