### ISSUE TITLE
Dual Monitor setup 

### ISSUE THREAD

**Issue by ViralShastri** [janleigh/dotfiles#35]
Hey, I need your help with something. So i wanted to use your dot files for my fresh Arch Linux Distro. I wanted to ask you that will it work with dual monitor setup?

Amazing Job on the Rice BTW, Thanks for providing us the Dots🙏

**Comment by janleigh** [comment]
I think it should work but not tested since I don't use a dual monitor setup.

**Comment by ViralShastri** [comment]
Thanks @janleigh , I'll test it out then
